name: Feature request
description: Propose an improvement
title: "feat: "
labels: [enhancement]

body:
  - type: textarea
    attributes:
      label: Use case
      description: Describe the problem this feature would solve.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed behavior
      description: Describe how you would expect scrapy-flaresolverr to behave.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: Describe any alternative approaches or workarounds you considered.
    validations:
      required: false
